### PR TITLE
libtf: added support for regression models

### PR DESCRIPTION
**Pull request by tejalbarnwal**
The PR is about feature requested for [Issue 1751](https://github.com/openmv/openmv/issues/1751) and [Issue 1739](https://github.com/openmv/openmv/issues/1739)

Added function `libtf_regression_1Dinput_1Doutput` to support the functionality of regression models for one-dimensional input array and one-dimensional output array
Presently, it supports only `int8`, `uint8`, and `float32` tflite models.

Python bindings for this added functionality can be found [here](https://github.com/tejalbarnwal/openmv/blob/master/src/omv/modules/py_tf.c#L260), which perfectly works for all boards except `OPENMV4_PRO`
You can find the built firmware for all other boards [here](https://github.com/tejalbarnwal/openmv/releases/tag/development).
Further, I need some of your help to debug the case for `OPENMV4_PRO`. I am not sure about the reason for it running out of memory. You can find the same error screenshot [here](https://github.com/tejalbarnwal/openmv/actions/runs/3780111637/jobs/6425928339#step:6:955).

I have tested the functionality on Arduino Nicla VIsion Board which works flawlessly.
The models used for testing can be found [here](https://github.com/tejalbarnwal/openmv/tree/master/src/lib/libtf/models) which is a `float32` model.
Please find the screenshot attached below:
Screenshot from 2022-12-26 15-03-38

### CODE REVIEW

**Comment by iabdalkader** [comment]
I think maybe you missed something, because when I try to link with libtf I get an undefined reference:
```
in function `tflite::AllOpsResolver::AllOpsResolver()':
all_ops_resolver.cc:(.text._ZN6tflite14AllOpsResolverC2Ev+0x262): undefined reference to `tflite::Register_ETHOSU()'

all_ops_resolver.cc:(.text._ZN6tflite14AllOpsResolverC2Ev+0x26a): undefined reference to `tflite::GetString_ETHOSU()'
```

Might be this line in `make.py`
```
#        data = re.sub(r" tensorflow/lite/micro/kernels/ethosu.cc", "", data)
```

**Comment by tejalbarnwal** [comment]
Yeah, I actually had commented [this](https://github.com/openmv/tensorflow/blob/5d654474061243d8532b5845d334144338894635/tensorflow/lite/micro/all_ops_resolver.cc#L41) line in `tensorflow/lite/micro/all_ops_resolver.cc` to get around that error. The particular line is related to the `EthosU` operation.

Does commenting on the line in the `make.py` solve the issue?
I could also instead introduce those operations using the `libtf_init_op_resolver` function defined in the `libtf.cc`. I will uncomment some operations and remove the `tflite::AllOpsResolver` from the code. Shall I do that?

**Comment by iabdalkader** [comment]
Hi @tejalbarnwal , no this will need to be fixed `make.py`, the flatbuffers is just not copied to right path, will look into it, but in the mean time, I noticed this change adds about 177KBs to the final firmware image, this is why PRO doesn't build. We can't use that much flash for this feature, but it seems it can be fixed if you just use this instead:
```
        tflite::MicroMutableOpResolver<LIBTF_MAX_OPS> resolver;
```
It seems that the extra flash is consumed by the allops resolver enabling every possible op. You should test with the above and see if any ops are missing, if so you can just enable them one by one in `libtf.c`.

**Comment by tejalbarnwal** [comment]
Sure, I will do that!

**Comment by iabdalkader** [comment]
Note, so actually we won't have to fix `make.py` because `AddEthosU` will not be called. You just need to use the resolver above, and figure out the exact ops you need and enable them in `libtf.cc`

**Comment by tejalbarnwal** [comment]
@iabdalkader I removed the `removed all_op_resolver` instance and added ` tflite::MicroMutableOpResolver<LIBTF_MAX_OPS>` instance for resolver

Further, now I could build for `OPENMV4_PRO` as well as you see [here](https://github.com/tejalbarnwal/openmv/actions/runs/3785441783).
Thank you so much!

Please let me know when you are reviewing this, I also a submit a PR for python bindings to include the function in `pytf.c`

**Comment by iabdalkader** [comment]
Thanks, I can probably test it again today. If PRO is building it means the flash usage is at least 100K less which is very good. I'm just wondering, are all of the newly enabled ops actually needed ?

> I also a submit a PR for python bindings to include the function

I did not see this PR, you should send to `openmv/openmv` repo. Please don't update the libraries (`corext*/libtf.a`) I will rebuild them here first and update them, just send the needed changes to `py_tf.c`

https://github.com/openmv/openmv

**Comment by iabdalkader** [comment]
This is merged now, thanks! I've also updated the static libraries. You can now send the other PR to openmv, I suggest that you call the function `regression` for now, we can maybe add args later to specify dimensions.

**Comment by tejalbarnwal** [comment]
>Thanks, I can probably test it again today. If PRO is building it means the flash usage is at least 100K less which is very good. I'm just wondering, are all of the newly enabled ops actually needed ?

Yeah, they are different activation functions for the model

I have now added a PR for the python bindings in `openmv` repo

**Pull request merged**
